lng_bot_token_description: "Please enter your bot token to continue",
lng_bot_token_ph: "Bot Token",
lng_bot_token_submit: "Continue",
lng_bot_token_empty: "Please enter your bot token",
lng_bot_token_invalid: "Invalid bot token. Please check and try again.",
lng_bot_token_expired: "Bot token has expired. Please get a new token from @BotFather.",
lng_bot_token_network_error: "Network error. Please check your connection and try again.",
lng_bot_token_invalid_format: "Invalid token format. Bot tokens should contain a colon (:) separator.",
lng_bot_auth_error: "Failed to authenticate bot. Please check your token and try again.",
lng_bot_token_button: "Login as Bot",
lng_bot_restrictions_text: "Your bot has the following restrictions:",
lng_bot_restrictions_none: "Your bot has no special restrictions.",
lng_bot_restriction_messages: "• Can send messages",
lng_bot_restriction_media: "• Can send media",
lng_bot_restriction_stickers: "• Can send stickers",
lng_bot_restriction_gifs: "• Can send GIFs",
lng_bot_restriction_games: "• Can send games",
lng_bot_restriction_inline: "• Can use inline mode",
lng_bot_continue: "Continue",
lng_bot_mode_header: "Bot Mode",
lng_bot_mode_settings: "Bot Settings",
lng_bot_mode_commands: "• Has custom commands",
lng_bot_mode_description: "• Has description",
lng_bot_mode_join_groups: "• Can join groups",
lng_bot_mode_read_messages: "• Can read all group messages",
lng_bot_mode_inline: "• Has inline mode",
lng_bot_mode_no_restrictions: "No special restrictions",
lng_bot_mode_no_info: "No information available",
lng_bot_settings_title: "Bot Settings",
lng_bot_settings_description_ph: "Enter bot description...",
lng_bot_settings_inline_mode: "Enable inline mode",
lng_bot_settings_group_mode: "Enable group mode",
lng_bot_settings_read_messages: "Enable read messages",
lng_bot_settings_save: "Save",
lng_bot_settings_error_not_bot: "This account is not a bot",
lng_bot_settings_error_invalid: "Invalid bot settings",
lng_bot_settings_error_description_too_long: "Description is too long. Maximum length is 512 characters.",
lng_bot_settings_error_invalid_settings: "Invalid bot settings",
lng_bot_settings_error_unknown: "An error occurred while saving settings. Please try again.",
lng_bot_commands_title: "Bot Commands",
lng_bot_commands_button: "Show Commands",
lng_bot_commands_empty: "No Commands Available",
lng_bot_commands_close: "Close",
lng_bot_command_busy: "Another command is being processed. Please wait.",
lng_bot_command_empty: "Command cannot be empty.",
lng_bot_command_too_long: "Command is too long. Maximum length is 64 characters.",
lng_bot_command_invalid: "Invalid command format. Use only letters, numbers, and underscores.",
lng_bot_command_success: "Command executed successfully.",
lng_bot_command_error: "Failed to execute command. Please try again.",
lng_bot_command_processing: "Processing command...",
lng_bot_command_cancelled: "Command cancelled.",
lng_bot_command_timeout: "Command timed out. Please try again.",
lng_bot_command_network_error: "Network error. Please check your connection.",
lng_bot_command_server_error: "Server error. Please try again later.",
lng_bot_command_unauthorized: "Unauthorized. Please check your bot token.",
lng_bot_command_rate_limit: "Rate limit exceeded. Please wait before trying again.",
lng_bot_command_validation_error: "Invalid command parameters.",
lng_bot_command_unknown_error: "An unknown error occurred.",

// Bot Client Settings
lng_settings_bot_client: "Bot Client",
lng_settings_bot_logging_about: "Configure logging for bot operations",
lng_settings_bot_enable_logging: "Enable logging",
lng_settings_bot_log_path: "Log file path:",
lng_settings_bot_log_browse: "Browse",
lng_settings_bot_log_choose: "Choose log file location",
lng_settings_bot_log_debug: "Debug (Verbose)",
lng_settings_bot_log_info: "Info (Default)",
lng_settings_bot_log_warning: "Warning",
lng_settings_bot_log_error: "Error",
lng_settings_bot_log_critical: "Critical",

lng_settings_bot_autostart_about: "Configure how the bot client starts",
lng_settings_bot_autostart: "Start with system",
lng_settings_bot_minimize_tray: "Minimize to tray when closed",
lng_settings_bot_start_minimized: "Start minimized",

lng_settings_bot_privacy_about: "Configure security and privacy options",
lng_settings_bot_secure_connection: "Use secure connections only",
lng_settings_bot_local_proxy: "Use local proxy for network requests",
lng_settings_bot_encrypt_logs: "Encrypt log files",

lng_settings_bot_updates_about: "Configure bot client updates",
lng_settings_bot_auto_update: "Update automatically",
lng_settings_bot_update_stable: "Stable channel",
lng_settings_bot_update_beta: "Beta channel",
lng_settings_bot_update_dev: "Development channel",
lng_settings_bot_check_now: "Check for updates",
lng_settings_bot_update_checking: "Checking for updates...",
lng_settings_bot_update_latest: "You have the latest version",
lng_settings_bot_update_available: "Update available",
lng_settings_need_restart: "Changes will take effect after restart" 